server:
  port: 8090
  #feishu.EncryptKey=FXNs61zHHXeFUonzNpb4yeTiu18H0YFQ
feishu:
  VerificationToken:
  app_id:
  app_secret:
  approval_code_reimbursement:
  approval_code_payment:
kingdee:
  acctId: 6426d47ba9ad91
  username: 王典
  password: 888888
  lcid: 2052
  serverurl: http://172.16.100.161//k3cloud/
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:

          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://localhost:1433;database=feishu
          username: sa
          password: qwert
          druid:
            validation-query: SELECT 1
#          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#          url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=feishu
#          username: sa
#          password: qwert
#          druid:
#            validation-query: SELECT 1

        # mybatis-plus通用配置
mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: false