
server:
  port: 8090
  #feishu.EncryptKey=FXNs61zHHXeFUonzNpb4yeTiu18H0YFQ
feishu:
  VerificationToken: cdriYsmGeHdwf2d8WG68rfLgSw3sejN7
  app_id: cli_a2edfada0538100b
  app_secret: SENn7dB9FJaSGeyNg8Bxne4mY0OQtjXz
  approval_code_reimbursement: 7312B2C7-5E94-4F55-9ED5-578D9104F1AB
  approval_code_payment: 566B93DE-ACD9-4288-A861-EF7CDFB352B0
kingdee:
  acctId: 6369ebd98ea40b
  username: administrator
  password: 888888
  lcid: 2052
#  serverurl: http://nayun2020.yicp.io/k3cloud/
  serverurl: http://192.168.50.16/k3cloud/
#spring:
#  datasource:
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://192.168.50.16:1433;DatabaseName=feishu
#    username: sa
#    password: sa@123
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 1
#    testWhileIdle: rue
#    testOnBorrow: true
#    testOnReturn: true
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://192.168.50.16:1433;DatabaseName=fishu
          username: sa
          password: sa@123
          druid:
            validation-query: SELECT 1

        # mybatis-plus通用配置
mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: false